### ISSUE TITLE
Add an onClose event to Window

### ISSUE THREAD

**Issue by mdindoffer** [teamapps-org/teamapps#119]
`org.teamapps.ux.component.window.Window` can be closed with either the `ESC` key, via the close button, or simply by clicking outside the window.

Unfortunately, there is no way to intercept this and perform additional actions when closing the window.

Please add an `onClose` event hook for this action.

**Comment by yamass** [comment]
Closed by c6589d5ec0011a6328015b569039da2d173e1dbe
