### ISSUE TITLE
text input field does only update value on focus in/out

### ISSUE THREAD

**Issue by XDjackieXD** [teamapps-org/teamapps#21]
text input fields do not update their value when something pastes into them that doesn't trigger focus events (some password managers like pass-ff do this).
At least when the according submit button is pressed the current field values shall be used and not their "shadow copies" as this behaviour is unexpected and breaks some things.

**Comment by yamass** [comment]
Fixed with bf2d8913e98c334a5ea7f5fe72ecb5047fbe0db8
